### ISSUE TITLE
the aleo.exe run is wrong,windowns 10

### ISSUE THREAD

**Issue by leevcc** [hpool-dev/aleo-miner#1]
hi,i have a problem
it does not read the config.yaml 

D:\aleo>aleo
***************************************************
**** Miner:HPool-Miner-ALEO
**** Version:v1.0.0 2
**** BuildTime:2021-12-28-10:24:53 GMT
**** MinerName:MS-NVDNCVWTCUHP
**** ApiKey:
**** Thread Num:0
**** Mine Num:0
**** Warning: This is a test network
***************************************************
panic: 请先配置矿池ApiKey!!
Please configure the mining pool ApiKey first!!

goroutine 1 [running]:
hpool.com/dev/miner-client/platform.Run(0xc000121f50, 0xc000067aa0, 0x7ff75207a6b8, 0xc0001a6240)
        platform/console.go:54 +0x8d9
main.main()
        main.go:152 +0x4ab

congfig.yaml
minerName:"lh"
apiKey: aleo0000-634e-4c5c-a1af-a593bd320a31
log:
  lv: info
  path: ./log/
  name: miner.log
url:
  proxy: "http://192.168.1.4:9190"
proxy:
    # E.g http://127.0.0.1:8888 socket5://127.0.0.1:8888
    url: ""
    username: ""
    password: ""
language: cn
line: cn

extraParams:
  proveFile: "posw.proving.b2d14c7"
  mineNum: "2"
  threadNum: "8"

**Comment by litingqu18** [comment]
我闪退

**Comment by pangsitao** [comment]
IMO, in your .yaml, you can try insert quotation to the apiKey field.
: 
apiKey: "aleo0000-634e-4c5c-a1af-a593bd320a31"
